name: veloura
description: A premium privacy-first long-distance couple communication application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.9

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Animations
  flutter_animate: ^4.5.0

  # Fonts
  google_fonts: ^6.2.1

  # QR code generator
  qr_flutter: ^4.1.0

  # UUID for IDs
  uuid: ^4.3.3

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
